<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  
<xacro:property name="border_offset" value="0.055" />

<!-- conversions -->
<!-- I couldn't make the simulation work with realistic values, so I tweaked the conversion values -->
<xacro:property name="mm_to_m" value="0.001"/>
<xacro:property name="mm2_to_m2" value="0.001"/>
<xacro:property name="gr_to_Kg" value="0.01"/>

<!-- not so negligible, otherwise simulation fails -->
<xacro:property name="negligible_mass" value="${10*gr_to_Kg}"/>
<xacro:property name="negligible_inertia">
    <origin xyz="0 0 0"/>
    <mass value="${negligible_mass}"/>
    <inertia ixx="${negligible_mass * 10 * mm2_to_m2}" ixy="0.0" ixz="0.0" iyy="${negligible_mass * 10 * mm2_to_m2}" iyz="0.0" izz="${negligible_mass * 10 * mm2_to_m2}"/>
</xacro:property>

<xacro:macro name="model_shelf" params="parent name *origin length width height plate_thickness color">
    <joint name="${parent}_${name}_base_joint" type="fixed">
        <xacro:insert_block name="origin"/>
        <parent link="${parent}"/>
        <child link="${name}_plate_link"/>
    </joint>
    <link name="${name}_plate_link">
        <inertial>
            <xacro:insert_block name="negligible_inertia"/>
        </inertial>
        <visual>
            <origin xyz="${1/2 * length} ${-1/2 * width} ${-1/2 * plate_thickness + height}"/>
            <geometry>
                <box size="${length} ${width} ${plate_thickness}"/>
			</geometry>
			<material name="Vito/${color}"/>
		</visual>
        <collision>
            <origin xyz="${1/2 * length} ${-1/2 * width} ${-1/2 * plate_thickness + height}"/>
            <geometry>
                <box size="${length} ${width} ${plate_thickness}"/>
            </geometry>
        </collision>
    </link>

    <gazebo reference="${name}_plate_link">
        <!-- <static>true</static> -->
    </gazebo>
    
</xacro:macro>
</robot>
