<?xml version="1.0"?>
<robot xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor" 
       xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller" 
       xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface" 
       xmlns:xacro="http://ros.org/wiki/xacro">
 
  <xacro:include filename="$(find youbot_description)/urdf/youbot_base/base.gazebo.xacro"/>
  <xacro:include filename="$(find youbot_description)/urdf/youbot_base/base.transmission.xacro"/>

  <!-- simplified box collision geometry for base -->
  <property name="base_size_x" value="0.570"/>
  <property name="base_size_y" value="0.360"/>
  <property name="base_size_z" value="0.100"/>
  <property name="base_mass" value="22.0"/>

  <property name="caster_offset_x" value="0.228"/>
  <property name="caster_offset_y" value="0.158"/>
  <property name="caster_offset_z" value="-0.034"/>
  <property name="caster_mass" value="0.1"/>

  <property name="wheel_offset_x" value="0.0"/>
  <property name="wheel_offset_y" value="0.0"/>
  <property name="wheel_offset_z" value="0.0"/>

  <property name="wheel_mass" value="1.4"/>
  <property name="wheel_radius" value="0.0475"/>
  <property name="wheel_length" value="0.005"/>

  <property name="caster_joint_damping" value="1.0"/>
  <property name="caster_joint_friction" value="1.0"/>
  <property name="caster_joint_effort" value="30"/>
  <property name="caster_joint_velocity" value="10"/>
  <property name="caster_joint_safety_k_velocity" value="10.0"/>

  <property name="wheel_joint_damping" value="1.0"/>
  <property name="wheel_joint_friction" value="1.0"/>
  <property name="wheel_joint_effort" value="30"/>
  <property name="wheel_joint_velocity" value="10"/>
  <property name="wheel_joint_safety_k_velocity" value="10.0"/>

  <property name="p_joint_effort" value="30"/>
  <property name="p_joint_velocity" value="10"/>
  <property name="px_lower_limit_def" value="-2"/>
  <property name="px_upper_limit_def" value="2"/>
  <property name="py_lower_limit_def" value="-1"/>
  <property name="py_upper_limit_def" value="1"/>

  <xacro:macro name="tinoBot" params="parent name *origin px_lower_limit:=${px_lower_limit_def} px_upper_limit:=${px_upper_limit_def} py_lower_limit:=${py_lower_limit_def} py_upper_limit:=${py_upper_limit_def}">

    <!-- <joint name="${name}_base_joint" type="fixed">
      <insert_block name="origin"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <parent link="${parent}"/>
      <child link="${name}_footprint"/>
    </joint> -->

    <joint name="${name}_base_p1_joint" type="prismatic">
      <insert_block name="origin"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <axis xyz="1 0 0"/>
      <limit lower="${px_lower_limit}" upper="${px_upper_limit}" effort="${p_joint_effort}" velocity="${p_joint_velocity}"/>
      <parent link="${parent}"/>
      <child link="${name}_footprint_p1"/>
    </joint>

    <link name="${name}_footprint_p1"/>

    <joint name="${name}_base_p2_joint" type="prismatic">
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <limit lower="${py_lower_limit}" upper="${py_upper_limit}" effort="${p_joint_effort}" velocity="${p_joint_velocity}"/>
      <parent link="${name}_footprint_p1"/>
      <child link="${name}_footprint_p2"/>
    </joint>

    <link name="${name}_footprint_p2"/>

    <joint name="${name}_base_p3_joint" type="continuous">
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <axis xyz="0 0 1"/>
      <limit effort="${caster_joint_effort}" velocity="${caster_joint_velocity}"/>
      <parent link="${name}_footprint_p2"/>
      <child link="${name}_footprint"/>
    </joint>

    <link name="${name}_footprint">
      <inertial>
        <mass value="0.1"/>
        <origin xyz="0 0 ${-base_size_z / 2.0}" rpy="0 0 0"/>
        <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0"/>
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="0.001 0.001 0.001"/>
        </geometry>
        <material name="youBot/Red"/>
      </visual>
      <collision>
        <origin xyz="0 0 ${-base_size_z / 2.0}" rpy="0 0 0"/>
        <geometry>
          <box size="0.001 0.001 0.001"/>
        </geometry>
      </collision>
    </link>
    <joint name="${name}_footprint_joint" type="fixed">
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <child link="${name}_link"/>
      <parent link="${name}_footprint"/>
    </joint>

    <joint name="${name}_ee_joint" type="fixed">
      <origin xyz="0 0 0.025" rpy="0 0 0"/>
      <parent link="${name}_footprint"/>
      <child link="${name}_ee"/>
      <!-- <child link="belt0_p"/> -->
    </joint>

    <!-- <link name="belt0_p"> -->
    <link name="${name}_ee">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="0.001 0.001 0.001"/>
        </geometry>
        <material name="youBot/DarkGrey"/>
      </visual>
    </link>

    <link name="${name}_link">
      <inertial>
        <mass value="${base_mass}"/>
        <origin xyz="0 0 0"/>
        <inertia ixx="5.652232699207" ixy="-0.009719934438" ixz="1.293988226423" iyy="5.669473158652" iyz="-0.007379583694" izz="3.683196351726"/>
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://youbot_description/meshes/youbot_base/base.dae"/>
        </geometry>
        <material name="youBot/DarkGrey"/>
      </visual>
      <visual>
        <origin xyz="${caster_offset_x+wheel_offset_x} ${caster_offset_y+wheel_offset_y} ${caster_offset_z+wheel_offset_z}" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${wheel_radius}"/>
        </geometry>
        <material name="youBot/Orange"/>
      </visual>
      <visual>
        <origin xyz="${caster_offset_x+wheel_offset_x} ${-caster_offset_y+wheel_offset_y} ${caster_offset_z+wheel_offset_z}" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${wheel_radius}"/>
        </geometry>
        <material name="youBot/Orange"/>
      </visual>
      <visual>
        <origin xyz="${-caster_offset_x+wheel_offset_x} ${caster_offset_y+wheel_offset_y} ${caster_offset_z+wheel_offset_z}" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${wheel_radius}"/>
        </geometry>
        <material name="youBot/Orange"/>
      </visual>
      <visual>
        <origin xyz="${-caster_offset_x+wheel_offset_x} ${-caster_offset_y+wheel_offset_y} ${caster_offset_z+wheel_offset_z}" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${wheel_radius}"/>
        </geometry>
        <material name="youBot/Orange"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <!--<box size="${base_size_x} ${base_size_y} ${base_size_z}" />-->
          <mesh filename="package://youbot_description/meshes/youbot_base/base_convex.dae"/>
        </geometry>
      </collision>
    </link>

    <!-- <joint name="${name}_link_wheels" type="fixed">
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <child link="${name}_wheels"/>
      <parent link="${name}_link"/>
    </joint>
    <link name="${name}_wheels">
      <visual>
        <origin xyz="${caster_offset_x+wheel_offset_x} ${caster_offset_y+wheel_offset_y} ${caster_offset_z+wheel_offset_z}" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${wheel_radius}"/>
        </geometry>
        <material name="youBot/Orange"/>
      </visual>
      <visual>
        <origin xyz="${caster_offset_x+wheel_offset_x} ${-caster_offset_y+wheel_offset_y} ${caster_offset_z+wheel_offset_z}" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${wheel_radius}"/>
        </geometry>
        <material name="youBot/Orange"/>
      </visual>
      <visual>
        <origin xyz="${-caster_offset_x+wheel_offset_x} ${caster_offset_y+wheel_offset_y} ${caster_offset_z+wheel_offset_z}" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${wheel_radius}"/>
        </geometry>
        <material name="youBot/Orange"/>
      </visual>
      <visual>
        <origin xyz="${-caster_offset_x+wheel_offset_x} ${-caster_offset_y+wheel_offset_y} ${caster_offset_z+wheel_offset_z}" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${wheel_radius}"/>
        </geometry>
        <material name="youBot/Orange"/>
      </visual>
    </link> -->

  </xacro:macro>
</robot>

