string command
planner_item source
planner_item destination
uint64 object_id
string object_name
float64 time
planner_item[] filtered_source_nodes
planner_item[] filtered_target_nodes
---
bool ack
planner_item[] path